<a href="https://colab.research.google.com/github/GopuJayaAkash/week1-ai-foundations/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [ ]:
print(a + b)   # Addition
print(a - b)   # Subtraction
print(a * b)   # Element-wise multiplication
print(a / b)   # Element-wise division
print(a ** 2)  # Power

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[ 1  4  9 16]


In [ ]:
print(a + 10)  #Scalar addition
print(a * 2)   #Scalar multiplication


[11 12 13 14]
[2 4 6 8]


In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.shape)   # Dimensions
print(arr.ndim)    # Number of dimensions
print(arr.size)    # Total elements
print(arr.dtype)   # Data type

(2, 3)
2
6
int64


In [ ]:
print(a[0])      # First element
print(a[-1])     # Last element
print(a[1:3])    # Slice


1
4
[2 3]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

reshaped = arr.reshape(2, 3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(np.sum(a))
print(np.mean(a))
print(np.max(a))
print(np.min(a))
print(np.std(a))

10
2.5
4
1
1.118033988749895


In [ ]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(A @ B)          # Matrix multiplication
print(np.transpose(A))

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


In [ ]:
np.zeros((2, 3))   # All zeros
np.ones((2, 3))    # All ones
np.eye(3)          # Identity matrix
np.arange(0, 10, 2)
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
print(a > 2)
print(a[a > 2])   # Filtering

[False False  True  True]
[3 4]


In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr + 10)

[[11 12 13]
 [14 15 16]]
